AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  MacsFrameworkMasterRole:
    Description: Name of MACS Framework Master Role
    Default: arn:aws:iam::558705036680:role/macs-framework-master
    Type: String
  MacsFrameworkEventBusArn:
    Description: MACS Framework Event Bus ARN
    Default: arn:aws:events:us-east-1:558705036680:event-bus/macs-framework
    Type: String
Resources:
  MacsFrameworkCrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS:
                - !Sub ${MacsFrameworkMasterRole}
              Service:
                - events.amazonaws.com
      Description: Permissions required by AWS Cloud Security CSPM tool MACS Framework
      Policies: 
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetBucketPublicAccessBlock
                  - s3:GetBucketLogging
                  - s3:GetBucketTagging
                  - s3:GetBucketPolicy
                  - rds:DescribeDBInstances
                  - rds:ListTagsForResource
                  - storagegateway:DescribeGatewayInformation
                  - batch:DescribeJobDefinition
                  - storagegateway:DescribeChapCredentials
                  - storagegateway:DescribeCachediSCSIVolumes
                  - storagegateway:DescribeStorediSCSIVolumes
                Resource: "*"
          PolicyName: macs-evaluation
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutBucketPublicAccessBlock
                  - s3:PutBucketLogging
                  - s3:PutBucketPolicy
                  - rds:StopDBInstance
                  - rds:ModifyDBInstance
                  - storagegateway:DeleteGateway
                  - storagegateway:DeleteVolume
                Resource: "*"
          PolicyName: macs-remediation
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource: !Sub ${MacsFrameworkEventBusArn}
          PolicyName: macs-event-capture
      RoleName: macs-framework
      Tags:
        - Key: costcenter
          Value: 103364
        - Key: contact
          Value: cloud_security@micron.com
        - Key: application
          Value: MACS
        - Key: environment
          Value: Prod
        - Key: tier
          Value: 2
